### ISSUE TITLE
use pl.py prior to scoring

### ISSUE THREAD

**Issue by CLG68** [HBioquant/DiffBind#11]
Hi,

Is it possible to call pl.py just before scoring such as through an argument of predict.py?  If I call it after predict.py is done with scoring, the score would not reflect exactly a relaxed poses.  

Best,
Christian

**Comment by CLG68** [comment]
Trying pl.py was not a success:

(diffbindfr) christian@christian-linux01:/media/christian/VS/VS/VS_DiffBindFR/DiffBindFR/relax$ python pl.py ../app/MC4R_test/MC4R_debug/structures -nb 12 -v
INFO: Pandarallel will run on 12 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.
   0.00%                                          |        0 /       11 |      
   0.00%                                          |        0 /       11 |      
   0.00%                                          |        0 /       11 |      
   0.00%                                          |        0 /       11 |      
   0.00%                                          |        0 /       11 |      
   0.00%                                          |        0 /       11 |      
   0.00%                                          |        0 /       10 |      
   0.00%                                          |        0 /       10 |      
   0.00%                                          |        0 /       10 |      
   0.00%                                          |        0 /       10 |      
   0.00%                                          |        0 /       10 |      
   0.00%                                          |        0 /       10 |      multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/christian/anaconda3/envs/diffbindfr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/christian/anaconda3/envs/diffbindfr/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/christian/anaconda3/envs/diffbindfr/lib/python3.9/site-packages/pandarallel/core.py", line 95, in __call__
    result = self.work_function(
  File "/home/christian/anaconda3/envs/diffbindfr/lib/python3.9/site-packages/pandarallel/data_types/dataframe.py", line 32, in work
    return data.apply(
  File "/home/christian/anaconda3/envs/diffbindfr/lib/python3.9/site-packages/pandas/core/frame.py", line 10361, in apply
    return op.apply().__finalize__(self, method="apply")
  File "/home/christian/anaconda3/envs/diffbindfr/lib/python3.9/site-packages/pandas/core/apply.py", line 916, in apply
    return self.apply_standard()
  File "/home/christian/anaconda3/envs/diffbindfr/lib/python3.9/site-packages/pandas/core/apply.py", line 1063, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/home/christian/anaconda3/envs/diffbindfr/lib/python3.9/site-packages/pandas/core/apply.py", line 1081, in apply_series_generator
    results[i] = self.func(v, *self.args, **self.kwargs)
  File "/home/christian/anaconda3/envs/diffbindfr/lib/python3.9/site-packages/pandarallel/progress_bars.py", line 214, in closure
    return user_defined_function(
  File "/media/christian/VS/VS/VS_DiffBindFR/DiffBindFR/relax/pl.py", line 694, in process
    relax_pl(
  File "/media/christian/VS/VS/VS_DiffBindFR/DiffBindFR/relax/pl.py", line 526, in relax_pl
    modeller.add(lig_top.to_openmm(), ligand_mol.conformers[0])
  File "/home/christian/anaconda3/envs/diffbindfr/lib/python3.9/site-packages/openmm/app/modeller.py", line 132, in add
    newPositions.append(deepcopy(addPositions[atom.index]))
  File "/home/christian/anaconda3/envs/diffbindfr/lib/python3.9/site-packages/openmm/unit/quantity.py", line 773, in append
    raise TypeError("Cannot append item without units into list with units")
TypeError: Cannot append item without units into list with units
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/christian/VS/VS/VS_DiffBindFR/DiffBindFR/relax/pl.py", line 763, in <module>
    minimizer(
  File "/media/christian/VS/VS/VS_DiffBindFR/DiffBindFR/relax/pl.py", line 706, in minimizer
    df.parallel_apply(process, axis=1)
  File "/home/christian/anaconda3/envs/diffbindfr/lib/python3.9/site-packages/pandarallel/core.py", line 333, in closure
    results_promise.get()
  File "/home/christian/anaconda3/envs/diffbindfr/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
TypeError: Cannot append item without units into list with units

**Comment by CLG68** [comment]
I ended up creating my own script to take care of minimization
