### ISSUE TITLE
KeyError: 'l-rmsd'

### ISSUE THREAD

**Issue by haotianteng** [HBioquant/DiffBind#12]
I tried to evaluate the model on PDBBind dataset, but encounter the KeyError: 'l-rmsd', see below for detail messages. Could you help to look at what could be the problem? I also tried --debug parameters, but it gives the same error. 

2024-05-12 17:50:39,324 - Evaluator - INFO - Use benchmark libs: pb
2024-05-12 17:50:39,440 - Evaluator - INFO - Total loaded jobs: 428. 
2024-05-12 17:50:39,440 - Evaluator - INFO - Job Slice Info: (0, 428).
2024-05-12 17:50:39,440 - Evaluator - INFO - Running jobs: 428.
2024-05-12 17:50:39,446 - Evaluator - INFO - Start to prepare job (experiment name: posebusters).
Use Background Generator supported dataloader.
2024-05-12 17:50:39,451 - Evaluator - INFO - dock Status: Prep task is Done!
Initializing diffusion model...
2024-05-12 17:50:42,207 - Evaluator - INFO - load checkpoint from local path: /mnt/disk04/haotiant/DiffBindFR/DiffBindFR/weights/diffbindfr_paper.pth
2024-05-12 17:50:42,554 - Evaluator - INFO - Reload model inference output from /mnt/disk04/haotiant/DiffBindFR/pb/export/posebusters/results/model_output.pt
2024-05-12 17:50:42,556 - Evaluator - INFO - Export binding structures....
2024-05-12 17:50:42,556 - Evaluator - INFO - Binding structure export is completed.
2024-05-12 17:50:42,556 - Evaluator - INFO - Start to binding conformation enrichment analysis...
Traceback (most recent call last):
  File "/mnt/disk04/haotiant/DiffBindFR/DiffBindFR/evaluation/eval.py", line 276, in <module>
    runner(df, args)
  File "/mnt/disk04/haotiant/DiffBindFR/DiffBindFR/evaluation/eval.py", line 144, in runner
    pd_df, eval_results_df = out_fn(
  File "/mnt/disk04/haotiant/DiffBindFR/DiffBindFR/evaluation/eval.py", line 86, in out_fn
    ptb = report_enrichment(eval_results_df, show_reports = show_reports)
  File "/mnt/disk04/haotiant/DiffBindFR/DiffBindFR/evaluation/reporter.py", line 40, in report_enrichment
    l_rmsd = eval_results_df['l-rmsd']
KeyError: 'l-rmsd'

**Comment by HBioquant** [comment]
Hi, @haotianteng,

The problem behind this error may be that you didn't run any conformation on the posebusters dataset. Please check the error you printed at the initial run time and return it to me.

Best.
